### ISSUE TITLE
jargroup_getlatest() fails

### ISSUE THREAD

**Issue by lukehasnoname** [msmhq/msm#116]
I get the error of "URL downloaded multiple files" even when I verify the $num_files value is returning 1. I don't know enough about bash or the script to try to fix it...

My workaround was to disable the num_files check completely. Things work just fine now.

I was using the official minecraft_server.jar link from the doc.

(PS feature: include error codes and make a doc for that.)

**Comment by renderorange** [comment]
this bug is no longer present, closing to clean up old issue.
