### ISSUE TITLE
[Question] How to restore backups?

### ISSUE THREAD

**Issue by joecabezas** [msmhq/msm#212]
I see them in /opt/msm/archives/worlds/..., and I have to unzip them in worldstorage...

but msm have a "standard way" to restore backups?, a command maybe?

**Comment by lewischolcroft** [comment]
> I see them in /opt/msm/archives/worlds/..., and I have to unzip them in worldstorage...
> 
> but msm have a "standard way" to restore backups?, a command maybe?

It is also important to make sure ALL the files you restore to your world(s) folders have correct ownership. In my case a number of the files in backup were owned by the root user. My system is linux based. I used chown and chgrp commands to set ownership to minecraft and group to minecraft.
