### ISSUE TITLE
Project Stale or Dead?

### ISSUE THREAD

**Issue by tgstyle** [msmhq/msm#242]
Is msm even moving forward at all? Is it possible to get it revived? Someone else need to take over the reigns? This has been a great server manager for those who enjoy the light weight non-intrusive approach. I would like to see it get moving again for 1.7.2 and beyond.

**Comment by zachlatta** [comment]
Aaand we're back. Check out the discussion in #290.

We're now adding an open commit bit for MSM, so anyone who contributes gets the commit bit.
