### ISSUE TITLE
Current Version

### ISSUE THREAD

**Issue by kjkazinski** [msmhq/msm#251]
What is the current version of MSM?  I did a msm update.  The version listed was 0.8.16... Already at latest version.

If this is not the current version what do I need to do to get the current version?

**Comment by kjkazinski** [comment]
Will the script be updated to look here for any updates?

**Comment by kjkazinski** [comment]
As a minimum there should be a 0.9 version on Marcus' site that updates where MSM looks for the updates.

Has a new version been released?

**Comment by renderorange** [comment]
I haven't done any new updates to versioning, but yeah, now would be a good time to get it bumped for a new release.  Generally speaking, I've just been trying to get the project current, iron out any existing glaring issues, but not necessarily put in any new features.  I haven't had a ton of free time for this, but it's been my goal overall.

I've seen in a few threads here the issue of versioning, @marcuswhybrow, is there any specific process which would be important to relay for versioning?  Is there anyone else that might know the general process this project uses for versioning or releases?

I think as soon as the glaring issues have been sorted, bumping to a new version would be good.

**Comment by renderorange** [comment]
Perhaps we should start pulling together a list of issues to fix before an updated release is made?  I have a short list I've been working on, I could paste it in tomorrow, perhaps start a milestone for release?

**Comment by marcuswhybrow** [comment]
Logically versions work as according to https://github.com/msmhq/msm#versioning

It's important to understand MSM's update system works by downloading files from the `latest` tag: see [init/msm#L3257](https://github.com/msmhq/msm/blob/34c20dd869e75e107ca9e111b6866eb9d39120ee/init/msm#L3257). `latest` must therefore always point to the latest version tag.

I made a simple script to bump MSM's version tags (version tag and `latest` tag) which you can find here: [marcuswhybrow/gitbump](https://github.com/marcuswhybrow/gitbump)

**Comment by renderorange** [comment]
Thanks Marcus!  It makes good sense to me now.

**Comment by renderorange** [comment]
I've updated the versioning in the msm init, as well as the git tag for latest to match 0.9.0.  I've tested upgrade from the last tagged 0.8.16 to 0.9.0, all seems to be in order.  If anyone sees any issues in upgrading, please feel free to open this issue back up with comments.  Thanks!
