### ISSUE TITLE
uninstallation?

### ISSUE THREAD

**Issue by ovizii** [msmhq/msm#260]
Is it really this easy: http://msmhq.com/docs/uninstallation.html ? 
- what about the created user? 
- what about the created folder /dev/shm/msm ?
- how do we reverse "sudo update-rc.d msm defaults" ?

**Comment by ovizii** [comment]
Hi guys, any progress on more complete uninstall instructions please?

**Comment by zerog2k** [comment]
+1 would like to know how to uninstall

**Comment by codingvirtual** [comment]
Not that this is a "script," but you can do the following and at least find the rc files that need to be deleted:

cd /etc
find . | grep msm

(that's "find" then a period then a pipe then grep msm)
This should produce a list of files inside of the etc directory (and all subdirectories) that contain msm
Review the list carefully and delete appropriately with sudo rm <filename>

**Comment by ovizii** [comment]
thx for the detailed steps!
