### ISSUE TITLE
Mac Support For MSM

### ISSUE THREAD

**Issue by Timur-Rumit** [msmhq/msm#277]
There Should Be A Mac Version For MSM For Some People Use Macs For Running Their Servers.

**Comment by brandondrew** [comment]
Can you list the bash commands that gave you headaches?  I'm sure people could find alternatives that would work cross-platform, or find ways to make them work on OS X.  (Perhaps the solution would be as simple as installing GNU versions of commands and making sure they take precedence in the PATH.)

**Comment by forquare** [comment]
If there was a Mac version available, I think it should be fairly portable to BSD.
