### ISSUE TITLE
RFC: Move MSM to GitHub Organisation?

### ISSUE THREAD

**Issue by marcuswhybrow** [msmhq/msm#291]
#290 highlights how sole control of MSM's repo privileges (by me) is blocking progress. Moving to a GitHub org might solve all that, and let MSM breath again:

+ Within an org, admin rights are assignable to multiple people (via teams).
+ Admins can add collaborators (contemplated in #290)

Downsides?
- New repo endpoint
- Install/update endpoints changed

So I don't decide *for* everyone, let's discuss it here.

**Comment by renderorange** [comment]
In the nature of it being an open source project and moving towards a community driven one, I think that would be best to move it to an organization of its own.  My 2 cents.

**Comment by joecabezas** [comment]
as a first donator, I will put 3 cents here too :)

**Comment by marcuswhybrow** [comment]
That brings up donations. They should surely be made retroactively owned by the community somehow. However, I don't have much experience in how.

**Comment by zachlatta** [comment]
:+1: definitely for this.

**Comment by marcuswhybrow** [comment]
I'm thinking "msmhq" (to match http://msmhq.com) as the org name and "msm" (as opposed to "minecraft-server-manager") as the repo name.

That would make (a splendily short): https://github.com/msmhq/msm

**Comment by zachlatta** [comment]
:+1:

**Comment by renderorange** [comment]
Great naming ideas.

**Comment by marcuswhybrow** [comment]
OK. Let's make the move. Should we plan a time to switch over, or shall I go right ahead?

**Comment by OstlerDev** [comment]
I would go ahead and do it, just be sure to post a notice for users on this repository.

**Comment by marcuswhybrow** [comment]
Move complete:

1. Transitioned [marcuswhybrow/minecraft-server-manager][old] to [msmhq/msm][new]
2. Created @msmhq/core containing @zachlatta and me (admin rights)
3. Created @msmhq/collaborators containing @endofcake and @renderorange (write rights)
4. Transitioned all links at [msmhq.com/index.html][home] to point to the new repo
5. Made a [blog][blog] post explaining how we're opening MSM's tomb

[old]: https://github.com/marcuswhybrow/minecraft-server-manager
[new]: https://github.com/msmhq/msm
[home]: http://msmhq.com
[blog]: http://msmhq.com/blog/

**Comment by zachlatta** [comment]
:+1:
