### ISSUE TITLE
Make java an MSM installation dependency?

### ISSUE THREAD

**Issue by marcuswhybrow** [msmhq/msm#295]
PR #236 added `sudo yum install java` to the `install_dependencies` stage of `installers/redhat.sh`. We don't require Java be installed in `installers/arch.sh` or `installers/debian.sh`.

_Should Java be consistently required across all distros?_ Java is **not** integral to MSM's logic. Java just happens to be used the "invocation" defined in MSM's settings. In theory this invocation command could be anything; although we all know it's going to use Java.

Thoughts?

**Comment by renderorange** [comment]
Should Java be consistent[...] across all distros?  I think definitely yes.  If we removed Java from the install requirements for redhat, it would be the easiest path to being consistent.  Although ultimately, the admin of the server will need to install java, else invocation is going to fail.

I guess the question is, *should* MSM take the responsibility of installing Java for them?  One issue in assuming installation would then be, which Java?  Oracle's version isn't available by default through Ubuntu's repos via apt-get, which Mojang themselves recommend using on their installation guide.  If we assume installation, it would be for OpenJDK.  Oracle's installation also requires accepting their EULA, which shouldn't be automated, IMO.

Should Java be consistently required across all distros?  Personally, I don't think so.  However, maybe having that be a part of the installation process, a (yes|no) question, would you like to install Java (OpenJDK), perhaps?  This would give the admin a means to decide, do I want to install Oracle's or OpenJDK, do I already have a version installed already, etc?

**Comment by endofcake** [comment]
@renderorange , I think it'd make sense to:

- check if java is available,
- if not, notify the admin and suggest to install the default version (which will be OpenJDK, I assume). 

If anyone needs to use Oracle's Java, they can do this manually. It used to be a pretty involved process as far as I can remember, luckily WebUpd8 team's PPAs simplify this greatly now (for Ubuntu at least).

**Comment by endofcake** [comment]
Fix merged in #442 .
