### ISSUE TITLE
server_log_dots_for_lines not returning dots on 1.8.7

### ISSUE THREAD

**Issue by renderorange** [msmhq/msm#301]
I haven't had time to investigate the reason, but the server_log_dots_for_lines() function being invoked within the server_start() function is not returning dots.

Instead, it's reaching timeout and breaking, which means server startup *seems* like it's taking longer to the admin (it's actually not taking any longer, just not returning anything to STDOUT).  If I remember correctly, it's 20 seconds vs 4 seconds.

Testing against a legacy server version, 1.5.2, the dots are displayed properly and the log break happens without issue, same msm code.

**Comment by marcuswhybrow** [comment]
I bet it's because the log format has changed slightly so `LOG_REGEX` won't match it: https://github.com/msmhq/msm/blob/0.9.2/init/msm#L61

**Comment by renderorange** [comment]
Testing in Pull Request #308 brings this bug into light, as well as another additional with the log file location.  Call for discussion over there.

**Comment by renderorange** [comment]
closing per fix
