### ISSUE TITLE
Manual installation instructions don't include user creation.

### ISSUE THREAD

**Issue by brandondrew** [msmhq/msm#304]
There's no mention in the [installation instructions](http://msmhq.com/docs/installation.html) of how/where/etc. to create a user.  This renders it useless to some portion of users.

**Comment by brandondrew** [comment]
I believe the fix is as simple as adding this to step 3 before the `chown` line
~~~
useradd minecraft  --home /opt/msm
~~~

**Comment by renderorange** [comment]
Hey, good find.  I'll go ahead and update the docs to include the needed commands.

**Comment by brandondrew** [comment]
If you find anything else missing please let me know--I'm baffled as to why I can't get this working... Thanks!

**Comment by renderorange** [comment]
pushed up a couple changes for the most recent updates.
https://github.com/msmhq/msm/commit/d8437b754ced1562f7cd6f60e24cba690fdcb0c7
https://github.com/msmhq/msm/commit/701fb050d662869fad5c9813f8239804f2408886
I'll hop over to your other issue, closing this one out for now.

**Comment by kjkazinski** [comment]
Brandon,
You have to create the user minecraft on your system.  Maybe the documentation is not clear that minecraft is an example user or if you want to use the named user 'minecraft' it needs to be created.
