### ISSUE TITLE
moving LOG_PATH to versioning file

### ISSUE THREAD

**Issue by renderorange** [msmhq/msm#309]
after discussion in pull request #308, it was agreed upon to move the LOG_PATH out to the versioning files, to support the difference between 1.3.0.sh and 1.7.0.sh.

I'm noting here the discussion points on the technical dynamics of the change.

@marcuswhybrow:
Versioning has only two declarative options: `console_command` and `console_event`. We'd need a to do two things to allow server properties to be set by versioning files:

1. Add a hook for setting properties in versioning files:

    ```
    # $1: The name of the property
    # $2: The value of the property
    set() {}
    ```

2. Rework `server_property` to also check versioning files declarations of properties if not found in `server.properties`.

---

The logic flow in `server_property` is a bit random:

* It's assumed version files can only declare a special group of property `CONSOLE_*` properties ([#L1793][#L1793]).
* If the property *is* of that class it will check the version file **and not** check `server.properties` ([#L1803][#L1803]).
* Loading from `server.properties` is a final catch-all that's attempted if no previous method of lookup has succeeded ([#L1818][#L1818]).

We'd need a new logic flow:

1. Check the version file regardless of property name (this would catch `CONSOLE_*` properties and all other types).
2. Don't check `server.properties` if it's a `CONSOLE_*` property. (We could check `server.properties` too if we wanted. But that would be a separate consideration and a new feature to document).
3. Check `server.properties` for all other cases.

[#L1793]: https://github.com/msmhq/msm/blob/0.9.2/init/msm#L1793
[#L1803]: https://github.com/msmhq/msm/blob/0.9.2/init/msm#L1803
[#L1818]: https://github.com/msmhq/msm/blob/0.9.2/init/msm#L1818

**Comment by donkers** [comment]
Got most of this done. :)   I have pushed it to a branch if you wish to have a look over the progress.
  https://github.com/donkers/msm/tree/versionable_properties

It is implemented almost exactly as outlined above. The exception being that in regards to note 1 in the logic, I am only checking version file on `CONSOLE_*` and `*_PATH` properties. But it has been coded so it can be easily changed in the future if required. Would just have to update the if condition and the new function(s) should deal.

I have tested a little with 1.2.5 and 1.7.10 but will do more before I submit a pull request.

Might do some minor re-factoring on the new code as well.
