### ISSUE TITLE
Can MSM be used with Hexxit server?

### ISSUE THREAD

**Issue by codingvirtual** [msmhq/msm#311]
Is it possible to use MSM to manage a Hexxit server?

**Comment by kjkazinski** [comment]
Yes it is.  You will have to change the links to point to the correct jar file but it is relatively painless.

**Comment by codingvirtual** [comment]
I was able to get it working. I had tried fixing the links but apparently something wasn't quite "right." I deleted the folder out of /opt/msm/servers and started over and it all works fine now.

Thanks!
