### ISSUE TITLE
What msm-version should I use if I'm running Spigot 1.8?

### ISSUE THREAD

**Issue by teaearlgraycold** [msmhq/msm#323]
It seems like others are running MSM with MC 1.8, although there doesn't seem to be official support past 1.7.

**Comment by FrozenBeard** [comment]
Snap, im in the same boat, I would love to run this but its not moved past 1.7 from what I can see

**Comment by teaearlgraycold** [comment]
I'm currently running it on "minecraft/1.7" without any issues so far.

**Comment by FrozenBeard** [comment]
We're leading up too 1.9 release, Are there any threads stating this works fine with 1.8? All I can see is it referencing ops.txt which is pre 1.7.2

**Comment by teaearlgraycold** [comment]
I guess I could look into forking this and making it strictly 1.8
compatible (just forgetting about anything pre 1.8, ops.txt vs. JSON op
storage etc.).

**Comment by FrozenBeard** [comment]
Sounds like an awesome idea to me, How has it been using it for a production server? im currently using Mark2 but the backups are wonky and I hate the GUI, I want a full screen/tmux front end. Hell with Tmux you can even have templates for laying out windows in a terminal, we could have a layout that shows htop and a player list!

**Comment by derrickmehaffy** [comment]
From what I can tell running this I have no issues running on 1.8 if @teaearlgraycold  has forked it, I'd love to take a look.

**Comment by madtomic** [comment]
Anyone have a working 1.8 for this?
