### ISSUE TITLE
too many arguments spam

### ISSUE THREAD

**Issue by Cealian** [msmhq/msm#327]
i updated msm from 0.8.16 to 0.9.4 and it spams /usr/local/bin/msm: line 1836: [: too many arguments
all the time while doing msm server list
like this: 

[INACTIVE] "servername" /usr/local/bin/msm: line 1836: [: too many arguments
is stopped. Everything is OK.

i have no idea whats wrong and if i need to do something to get the new version to work

**Comment by MiGeHo** [comment]
I just opened #330 with the same issue and a suggested fix.

**Comment by M-D-M** [comment]
Should be fixed with pull #346.
