### ISSUE TITLE
Hi problem with the server. 

### ISSUE THREAD

**Issue by Vis25** [msmhq/msm#329]
Hi,
I have problem with my server. I can be my own falt.
But i can't fix this so can you please help me i put the server file 
I trued to add another map to the server files and the new map "world" is not there.

When i start the server "msm WombatWorld start" i get no any kind of warning or error messages.
When command is completed and server supposed to be up in server list "msm server list" it show the server as closed.

Its problem is not about ports or IP. MAP files i think but really need your help with this.

Link to my server files : https://www.justbeamit.com/w5sjt 
I'm running another world and its working normaly.

**Comment by jrbooth3** [comment]
Did you edit the eula file in the root of your server/wombatworld folder
and try restarting the world?

**Comment by Vis25** [comment]
Its not about Eula.txt. In start server dosn't give eny errors or wasnigs it just but its not realy running

**Comment by jrbooth3** [comment]
Anything in the server / world logs?

**Comment by insuusvenerati** [comment]
`But i can't fix this so can you please help me i put the server file 
I trued to add another map to the server files and the new map "world" is not there.`

Can you please clarify? I don't understand what you are asking. It sounds like you added a new world to the worldstorage folder?

**Comment by Vis25** [comment]
This problem is all ready solved.. Thanks for your time

2016-03-17 1:53 GMT+02:00 Sean <notifications@github.com>:

> But i can't fix this so can you please help me i put the server file
> I trued to add another map to the server files and the new map "world" is
> not there.
>
> Can you please clarify? I don't understand what you are asking. It sounds
> like you added a new world to the worldstorage folder?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/msmhq/msm/issues/329#issuecomment-197610208>
>



-- 





Terveisin,

Vili-Aleksi Väisänen

Vili@kiho.fi

www.kiho.fi

https://www.facebook.com/kihopalvelu

Mastercom Oy

Asematie 3

71800 SIILINJÄRVI

FINLAND
