### ISSUE TITLE
-z test on line 1836 needs its argument quoted

### ISSUE THREAD

**Issue by MiGeHo** [msmhq/msm#330]
$ msm version
Minecraft Server Manager 0.9.4 Beta

$ msm all status
Server "s1" is running.
/usr/local/bin/msm: line 1836: [: too many arguments
Server "s2" is running.
/usr/local/bin/msm: line 1836: [: too many arguments

The culprit:

line 1836
if [ -z ${!target_varname} ]; then

${!target_varname} needs to be put in quotes:

if [ -z "${!target_varname}" ]; then

**Comment by morbeo** [comment]
If it isn't already obvious enough I created a PR for this #346 :)

**Comment by M-D-M** [comment]
Should be fixed with pull #346.
