### ISSUE TITLE
Is it possible to update a server from 1.8.4 to 1.9

### ISSUE THREAD

**Issue by otmezger** [msmhq/msm#332]
Hi, 

I've been playing minecraft with server version 1.8.4

```
msm-version=minecraft/1.8.4
```

Now I gut a client update to 1.9 and I was wondering if I can update my server to be compatible. I updated msm with

```
sudo mom update
$ sudo msm version
Minecraft Server Manager 0.9.4 Beta
```

I know I can change my profile on the client to be compatible with 1.8, but my question is if it is possible to change my world on the msm server to be compatible with 1.9 or if I need to start a new world. If it's possible, how? 

I tried to change this line in `server.properties`:

```
 msm-version=minecraft/1.9.0
```

bit it dod not work :-(. The world started but the client is still saying `Outdated Server. I'm still on 1.8.4`

Thanks

**Comment by insuusvenerati** [comment]
It should be msm-version=minecraft/1.9  not 1.9.0

**Comment by tjkrz** [comment]
Having the same issue. Set `msm-version=minecraft/1.9`. The client still claims the server is on 1.8.8.

**Comment by abaird** [comment]
Same here, my server.properties file is set to `msm-version=minecraft/1.9` but when I `tail -f log/latest.log` I get:
```
bash-4.2$ cat logs/latest.log
[14:51:52] [Server thread/INFO]: Starting minecraft server version 1.8.3
[14:51:52] [Server thread/INFO]: Loading properties
[14:51:52] [Server thread/INFO]: Default game type: SURVIVAL
[14:51:52] [Server thread/INFO]: Generating keypair
[14:51:53] [Server thread/INFO]: Starting Minecraft server on *:25567
[14:51:53] [Server thread/INFO]: Using epoll channel type
[14:51:53] [Server thread/INFO]: Preparing level "world"
[14:51:53] [Server thread/INFO]: Preparing start region for level 0
[14:51:54] [Server thread/INFO]: Preparing spawn area: 19%
[14:51:55] [Server thread/INFO]: Done (1.730s)! For help, type "help" or "?"
[15:00:15] [Server thread/INFO]: Turned off world auto-saving
[15:00:15] [Server thread/INFO]: Saving...
[15:00:15] [Server thread/INFO]: Saved the world
[15:00:15] [Server thread/INFO]: Turned on world auto-saving
```

...continuing to troubleshoot

**Comment by insuusvenerati** [comment]
Do you have a proper jargroup setup? Can you check the servers jar directory to see what version of the MC server jar is there?

**Comment by abaird** [comment]
here's what my jargroup looked like:
```
bash-4.2$ service msm jargroup list
minecraft
    2014-09-13-20-04-25-minecraft_server.1.8.jar
    2016-03-19-14-24-34-minecraft_server.1.9.jar
    2015-04-11-11-02-26-minecraft_server.1.8.3.jar
```
I still wasn't getting anywhere with that so I decided to delete everything thinking it would load the proper jarfile if 1.9 was the only one there. I executed the following commands:
```
service msm jargroup delete minecraft
service msm jargroup create minecraft https://s3.amazonaws.com/Minecraft.Download/versions/1.9/minecraft_server.1.9.jar
service msm jargroup getlatest minecraft
```
...which left me with:
```
bash-4.2$ service msm jargroup list
minecraft
    2016-03-19-15-10-39-minecraft_server.1.9.jar
```
After that, I had to update the individual server jar:
```
bash-4.2$ service msm alan-new restart now
Forcing save... Done.
Stopping the server... Done.
Synchronising worlds in RAM to disk... Done.
Could not find jar for server "alan-new": Expected "/opt/msm/servers/alan-new/server.jar".
bash-4.2$ service msm alan-new jar minecraft 2016-03-19-15-10-39-minecraft_server.1.9.jar
Server "alan-new" is now using "/opt/msm/jars/minecraft/2016-03-19-15-10-39-minecraft_server.1.9.jar".
bash-4.2$ service msm alan-new restart now
world
Maintaining world symbolic links... Done.
Synchronising flagged worlds on disk to RAM... Done.
Starting server................ Done.
bash-4.2$ cat logs/latest.log 
[15:12:50] [Server thread/INFO]: Starting minecraft server version 1.9
...
```
This got me to running with 1.9.

Unresolved questions:
1) Why didn't restarting with 1.9 in the jargroup pickup the latest version even after I made sure I updated server.properties to correctly point to 1.9?
2) Once I only had 1.9 in my jargroup, why did I have to manually set the `service msm <servername> jar <jarfile>` command?

I might try and troubleshoot a bit further later on today buy my daughters are begging me to play with them.  :)

**Comment by endofcake** [comment]
That's interesting, I've always update my servers by simply dropping the `server.jar` symlink and then recreatint to point at a newer jar. I've been running Minecraft Server Manager 0.9.2 Beta for quite a long time, in my `server.properties` I have `msm-version=minecraft/1.3.0`, yet in the server logs I see `Starting minecraft server version 1.9.2`, as expected.
