### ISSUE TITLE
PayPal Donations

### ISSUE THREAD

**Issue by marcuswhybrow** [msmhq/msm#338]
I'm still receiving, from when I was the sole contributor, the odd PayPal donation for MSM to my personal PayPal account.

I'd prefer MSM donations to be owned by the community somehow.

Anyone know a good solution?

**Comment by renderorange** [comment]
I think maybe it would give incentive for the community to step in to fix stuff, if bounties were used instead.  Maybe through https://www.bountysource.com ?

Updating the donate links (not really sure if there are any), to point to relevant places for bounties.  Not really sure how it works, but it would solve two problems, people wanting to donate, and getting people to step into fixing bugs.

**Comment by renderorange** [comment]
Commit cab6667 removes the donation link from the main page.
https://github.com/msmhq/msm/pull/425 removes additional donate links.

This issue should be safe to close, since it appears PayPal donations aren't advertised on the msm page anymore.

**Comment by M-D-M** [comment]
PR merged; closing.
