### ISSUE TITLE
Install Fails: run msm update; msm update fails

### ISSUE THREAD

**Issue by MECU** [msmhq/msm#342]
I'm on a CentOS server. I have root and am running the install command as root. This is a dedicated server with no head.

`wget -q http://git.io/lu0ULA -O /tmp/msm && bash /tmp/msm`

The first time I ran it, I didn't have the minecraft user created as system process (shouldn't the default be Y?), so I got more errors. After removing msm and `userdel minecraft`, I ran again with creating as a system user. Both ended up with this error:

```
MSM INSTALL: Asking MSM to update itself
[MSM Warning: Could not find versioning files, please use 'msm update' to download them]
Checking for updates to version 0.9.4...-bash: /bin/wget: Permission denied
sed: can't read /tmp/msmupdate/init/msm: No such file or directory
  is available.
Checking if any files need to be updated...-bash: /bin/wget: Permission denied
-bash: /bin/wget: Permission denied
/etc/init.d/msm: line 2235: /tmp/msmupdate/versioning/versions.txt: No such file or directory
 Done.
Updating will create the following files:
  > The bash completion script: /etc/bash_completion.d/msm
Updating MSM to :
mv: cannot stat ‘/tmp/msmupdate/bash_completion/msm’: No such file or directory
/etc/init.d/msm: line 2366: /etc/bash_completion.d/msm: No such file or directory
  > Created: /etc/bash_completion.d/msm
Done.
```

I do have /bin/wget owned by root (and it works, since the download script runs above).

It looks like it tries to run again:

```
[MSM Warning: Could not find versioning files, please use 'msm update' to download them]
Checking for updates to version 0.9.4...-bash: /bin/wget: Permission denied
sed: can't read /tmp/msmupdate/init/msm: No such file or directory
  is available.
Checking if any files need to be updated...-bash: /bin/wget: Permission denied
-bash: /bin/wget: Permission denied
/etc/init.d/msm: line 2235: /tmp/msmupdate/versioning/versions.txt: No such file or directory
 Done.
Updating will create the following files:
  > The bash completion script: /etc/bash_completion.d/msm
Do you want to continue [y/N]:
```
typing 'y' repeats the same two blocks of code. Entering N completes the install script with no other errors except for the MSM Warning.

Upon completion, I tried running `msm update`, but it ends with the same two blocks of error messages.

I started walking through the `/etc/init.d/msm` file for the update and after creating several files manually (around line 2232) and trying to run the `/opt/msm/init/msm` with no success or difference, I abandoned all hope of trying to figure it out myself.

Curiously, in `/tmp` the files `/tmp/msm` and directories `/tmp/msm-EID`, `/tmp/msm-iKr/` and `/tmp/msm-NeY/` exist where it seems that `/tmp/msmupdate` should exist. There are files in the directories:

```ls
-rw-r--r--  1 root root   8108 May 23 21:35 msm.conf
-rw-r--r--  1 root root   8108 May 23 21:35 msm.conf.orig
-rw-r--r--  1 root root    729 May 23 21:35 msm.cron
-rw-r--r--  1 root root    729 May 23 21:35 msm.cron.orig
-rw-r--r--  1 root root 126143 May 23 21:35 msm.init
-rw-r--r--  1 root root 126143 May 23 21:35 msm.init.orig
```

But sourcing the `msm.init` still gives:
```
[MSM Warning: Could not find versioning files, please use 'msm update' to download them]
```

**Comment by morbeo** [comment]
It seems that the **/tmp/msmupdate/versioning/** folder was missing with its file **versions.txt**. As discussed in #333 the version JSON was changed and most likely the update function will need to be updated as well.
