### ISSUE TITLE
Simple "Restart After Crash" Script?

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [msmhq/msm#343]
my server is a 1.8.9 modded server and is semi unstable, may crash once in a while and my players cannot play until i get on to a computer, i was wonderin if anyone had a simple "Restart After Crash" script, it recognizes that the server was shut off, so it runs that ./start file? any ideas??

**Comment by kjkazinski** [comment]
MSM has a cron job that can restart the server on the hour.

**Comment by EPIICTHUNDERCAT** [comment]
How does that work exactly, i have never used MSM, can you give me a bit more info? thank you so much for the reply!

**Comment by M-D-M** [comment]
@EPIICTHUNDERCAT Are you currently using MSM now, though?  (If not, welcome!  Read the installation instructions -- if they're too complex, you might want to get a nerdy friend to help). 

If so, once you've installed MSM, it has a cron job that restarts servers on the hour, if they're shut down -- you can find it in /etc/cron.d/msm.  It's the line that reads:

```
# Start any crashed servers again each hour
@hourly               mineuser   /etc/init.d/msm start
```

If you instead want this to run every five minutes, restarting any severs that have crashed, change this line to:

```
# Start any crashed servers again each hour
*/5  *   *   *   *   mineuser   /etc/init.d/msm start
```
