### ISSUE TITLE
disable worldstorage

### ISSUE THREAD

**Issue by SrBas97** [msmhq/msm#345]
As 'worldstorage' is disabled because it is a mess to create worlds

**Comment by morbeo** [comment]
Can you please elaborate what exactly are you inquiring? Do you want to disable worldstorage or it is disabled for you? What version of MC and MSM are you running? What help are you expecting?

**Comment by SrBas97** [comment]
MC version: 1.8.8, MSM version: latest
Disable worldstorage carpet, No direct carpet access

2016-10-26 14:32 GMT+02:00 Vladimir Kirov <notifications@github.com>:

**Comment by SrBas97** [comment]
To disable the worldstorage folder, and not have to put the worlds
inside that folder and create a shortcut


2016-12-01 13:23 GMT+01:00 manolitob <mjbp1997@gmail.com>:

**Comment by endofcake** [comment]
No clear issue here, closing.
