### ISSUE TITLE
Why so many processes ?

### ISSUE THREAD

**Issue by Inateno** [msmhq/msm#348]
Hi,

I've setup a server last weeks for trying msmhq.

This evening the server was laggy like hell, can't find why (no mods, small town, 3 players..)

After doing htop checkup I found this is not a normal behaviour since I made only 1 server and 1 world.

![image](https://cloud.githubusercontent.com/assets/1068709/20446467/07a061fe-adda-11e6-8bad-d34caf736816.png)

With a I5/4Go server I thought it would be okay for a while lol 4 years ago I was hosting a vanilla on a small home-hosted server.

Any advice ?

**Comment by OvermindDL1** [comment]
Put htop in tree mode (<F5>), you should see that those java processes are sub-processes of a main Java process, I.E., they are just the threads that minecraft spawn to do things like handle loading and network communication and such.  Seems that is the case since they all have the same Virtual memory size at least.  ^.^

**Comment by Inateno** [comment]
Okay but why it's using so much I can't figure out. No plugins at all, look insane.
Maybe a bug happen and I should load a backup ?

(PS: I just see I have the can't keep up message in the server console, maybe I should run it using Xms2048M - Xmx2048 ? How can I do it x) )

Also thanks for helping !

**Comment by Inateno** [comment]
Still the message with 2Go :/

**Comment by OvermindDL1** [comment]
> Okay but why it's using so much I can't figure out. No plugins at all, look insane.

No this is fairly normal now.  Minecraft has changed over time to add more threads to handle different things to make the main gamestate faster.  That is normal.

> PS: I just see I have the can't keep up message in the server console

You may see it only a time or two on first load or during chunk generation, if so you can ignore those.  If it is constant then your system sounds overloaded (cpu too slow or too little ram, neither of which seem to be your issue based on what your htop image shows).

**Comment by OvermindDL1** [comment]
> Still the message with 2Go :/

I've still no clue what you are referencing.  ;-)

**Comment by Inateno** [comment]
Lol sorry.
I've setup the server with 2048 M Ram (Xms2048 - Xmx2048, you see ?)
And still having the message.

Not everytime but we've got lot of rollback (walking them warp 20 block back)

**Comment by OvermindDL1** [comment]
> Lol sorry.
I've setup the server with 2048 M Ram (Xms2048 - Xmx2048, you see ?)
And still having the message.
> 
> Not everytime but we've got lot of rollback (walking them warp 20 block back)

Hmm, is it a modded server or vanilla?  What Java version?  What MC version?

**Comment by Inateno** [comment]
java version "1.7.0_111"
Minecraft vanilla latest.

:/

**Comment by OvermindDL1** [comment]
Definitely use Java 8 or higher first of all!
Latest minecraft practically requires Java 8, it has issues with 7.
So I'd change that first.

**Comment by Inateno** [comment]
I upgraded to the latest Java but still had the issue.
Then I moved to a Crafbukkit jar and seems far better (will se when playing with friends).

I thought with years Mojang's team had fixed their vanilla server but.... nop.

As my original question was answered I close this issue, thanks for the help.

**Comment by OvermindDL1** [comment]
> I thought with years Mojang's team had fixed their vanilla server but.... nop.

Indeed.  ;-)
