### ISSUE TITLE
Issue trying to the script install

### ISSUE THREAD

**Issue by memphistroth** [msmhq/msm#350]
So when it starts and does the apt-get update part it ends like this. How do i fix this?

Reading package lists... Done
W: The repository 'http://ftp.uk.debian.org/debian squeeze Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ftp.uk.debian.org/debian/dists/squeeze/main/binary-amd64/Packages  404  Not Found [IP: 78.129.164.123 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

MSM INSTALL ERROR: Couldn't update package list

**Comment by endofcake** [comment]
This sounds more like upstream Debian issue than MSM one, have you tried using a different mirror?
