### ISSUE TITLE
Can I put multiple jars in one jargoup???

### ISSUE THREAD

**Issue by sonic2005** [msmhq/msm#351]
I was reading the documentation and found this part: 

> <server> jar <jargroup> [<file>]
Sets a the jar file a server will use when starting up. If only a jar group is specified the latest jar in that group will be used. However if a file name is also given, it will be looked for in the jar group and used instead.

So does that mean there can be multiple jars in one jargroup???
Since we can specify the file name of the jar even after saying the jargroup name.
If I can how do I do it?? Is there a command for it???? Or should I do something manually???
If I can't, where can I use the [<file>] part in the <sever> jar <jargroup> command?
Pleae help!!!!

**Comment by M-D-M** [comment]
Yes -- it probably works a little differently now than in the past, but to add a new jar to a jargroup, use the following command: 
```msm jargroup changeurl <jargroupname> <download-url>```

Then get the latest file from the link you provided with: 
```msm jargroup getlatest <jargroupname>```

It will be added to the other available files in the jargroup. Then, for each server, you can specify which particular jarfile for that server with:
```msm <servername> jar <jargroupname> <jarfilename>```
