### ISSUE TITLE
MSM Does not start up

### ISSUE THREAD

**Issue by kjkazinski** [msmhq/msm#359]
I reinstalled my minecraft server on a new computer (VM) using Ubuntu.

Previously I have had no problems with MSM, but now my server does not start when I type msm <server name> start.  No error messages in the logs that I can see.

Any help?

Thanks.

**Comment by OnlyBrakeForRainbows** [comment]
Hi,

Java 8 is running? I once had a problem and it was multiple versions of Java:

`java - version` should indicate similar to '1.8.0_151'

This may help

**Comment by kjkazinski** [comment]
Hi Leo,

I am running openjdk version "9-Ubuntu"

Should I have installed a different version of Java?

Ken

**Comment by kjkazinski** [comment]
I uninstalled openjdk and reinstalled java using the java-default which installed openjdk version 1.8.0_151 and now everything is working.

**Comment by OnlyBrakeForRainbows** [comment]
Apologies for the late response, glad you are sorted now!
