### ISSUE TITLE
MSM server won't start. 

### ISSUE THREAD

**Issue by BarryBKS** [msmhq/msm#361]
Hi,

I am running MSM 0.9.5 Beta on Ubuntu 16.04 LTS.

I have had two servers running, one standard Minecraft, version 1.12.2 and a Tekkit, version 1.2.9.

My linux server had to do several updates and restarts, including upgrading to 18.04 LTS, recently and I went back on to the Tekkit server for the first time since today, to discover that none of my MSM servers are running.

If I enter $ sudo msm F_Tekkit start 
I get back: 
world 
Maintaining world symbolic links... Done. 
Synchronising flagged worlds on disk to RAM... Done. 
Starting server... 
It sits at the end of this line for about a minute, then returns Done. 
Excellent, so I enter $ sudo msm F_Tekkit status 
And I get back: 
Server "F_Tekkit" is stopped.

I checked in Tekkit and my server is still offline.

I am at a loss as to what has gone a miss. I cannot see any up to date logs to check and everything seems to be configured correctly.

Am I missing something?

Could upgrading from 16.04 to 18.04 have made any critical changes to the way MSM was installed / works?

Any altered system files were left as the originals during the upgrade so no manual changes were lost.

Any ideas most welcomed.

I will post copies of logs etc, if you wish to see them, but I cannot find any recent ones.

Will probably turn out to be something really simple that I am missing.

This has already been posted in the support forum, but I haven't had a response and was hoping posting here might help. 

Cheers,

Barry.

**Comment by kjkazinski** [comment]
Barry,
Start the server normally via command line without MSM and see if there are any errors.  Make sure the EULA is set to yes.

**Comment by BarryBKS** [comment]
kjkazinski,

Thanks for the reply.

I can confirm that the EULA is still set to true.

I don't know how to start the Minecraft server without running MSM?
I only have CLI, so everything is by command line.

Cheers,
Barry.

**Comment by BarryBKS** [comment]
I did as you suggested and this is the response I get:
barry@Linux1:/opt/msm/servers/F_Tekkit$ java -jar Tekkit.jar
We appear to be missing one or more essential library files.
You will need to add them to your server before FML and Forge will run successfu                                                                      lly.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinCla                                                                      ssLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(C                                                                      lassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:374)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.j                                                                      ava:30)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.                                                                      java:17)

I'm confused as to why these files have been lost unless it occurred in the OS upgrade? 
Any thoughts most welcomed.

**Comment by endofcake** [comment]
@BarryBKS , really hard to say without knowing your system, but if I were in a similar situation I'd try reinstalling Java and Minecraft from scratch.

At this point it is clear that this is not a problem with MSM, so closing this issue.
