### ISSUE TITLE
I am trying to load a custom world in to the server

### ISSUE THREAD

**Issue by Tech305** [msmhq/msm#373]
When ever i try to import a world that i created into the server i get this error 

> Error: Could not create link for world "spawn". The file "/opt/msm/servers/hub/spawn" already exists, and should not be overwritten automatically. Either remove this file, or rename "spawn".

and the server does not start how do i get this to work

**Comment by endofcake** [comment]
Have you tried removing `/opt/msm/servers/hub/spawn` and trying again?

**Comment by Tech305** [comment]
I have multiple times

**Comment by SteadBytes** [comment]
@Tech305 Are you still having issues with this?

**Comment by Tech305** [comment]
yeah I never got it working

**Comment by SteadBytes** [comment]
Still up for troubleshooting it? I will do what I can to help :+1:

**Comment by Tech305** [comment]
yeah I'm not home at the time but as soon as I get there I'll will

**Comment by SteadBytes** [comment]
Great, when you can, could you send the output of running `$ ls -al /opt/msm/servers/hub` please?

**Comment by endofcake** [comment]
Closed due to lack of activity.
