### ISSUE TITLE
Can run server with regular minecraft jargroup, can't run craftbukkit or spigot

### ISSUE THREAD

**Issue by NotEnoughMilk** [msmhq/msm#375]
I'n running my server on a digital ocean droplet running Ubuntu 16.04.5, and I can start my server just fine using the default minecraft jargroup, but when I change the jargroup to craftbukkit or any of the others I've tried to make, it says that the server has started up but when I do msm <servername> status, it says the server is stopped with nothing in the log (besides the last time it started with the minecraft jar).

I'm sure it has to be something obvious I'm missing, but I just can't seem to figure it out.

**Comment by Kadah** [comment]
Getting it working is tricky and I don't have those ticks I used handy. MSM lacks proper support for it so its hacky to get it to work.

For a new server from scratch, I would look at other options, MSM hasn't been maintained beyond same fixes in years.

**Comment by NotEnoughMilk** [comment]
Dang, that sucks, I kinda liked using it. Do you have any recommendations for what I can use instead?

**Comment by NotEnoughMilk** [comment]
I install pufferpanel and it a lot easier to use :D

**Comment by endofcake** [comment]
Good to see that you found a solution, @NotEnoughMilk .
Yes, this project is on life support unfortunately, the best we can hope to do right now is to keep it working when Minecraft is upgraded.
