### ISSUE TITLE
MSM Stopped Working After Ubuntu 18 Upgrade

### ISSUE THREAD

**Issue by kjkazinski** [msmhq/msm#376]
I recently upgraded from Ubuntu 17 to 18.

After I upgraded MSM no longer starts my vanilla version of minecraft.  When I start minecraft using the command line it starts with no issues.

Is there a log I can review?

**Comment by endofcake** [comment]
@kjkazinski , have you checked the `log` directory? For example, if `msm` is installed in `/opt/msm`, and your server is named `survival`, you can check `/opt/msm/servers/survival/logs`.

**Comment by endofcake** [comment]
You may also want to check your Java version, and see if https://github.com/msmhq/msm/issues/370 is similar to what you're seeing.

**Comment by kjkazinski** [comment]
Thanks guys that fixed it.
