### ISSUE TITLE
server start issues

### ISSUE THREAD

**Issue by slitterell** [msmhq/msm#378]
So, long story short I had to reinstall Ubuntu on my server. Before doing such, I was able to save the the entirety of the /opt/msm folder.

My first issue I had I found out to be Java crashing with there error:

OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'CMSIncrementalPacing'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

I removed "CMSIncrementalPacing' from:

DEFAULT_INVOCATION="java -Xms{RAM}M -Xmx{RAM}M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:+AggressiveOpts -jar {JAR} nogui"

It then start providing me with this error:

---- Minecraft Crash Report ----
// Don't do that.

Time: 6/23/19, 11:00 PM
Description: Exception in server tick loop

com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
        at zm.a(SourceFile:507)
        at zm.a(SourceFile:523)
        at xu.g(SourceFile:146)
        at uf.z(SourceFile:98)
        at uf.<init>(SourceFile:25)
        at ug.d(SourceFile:185)
        at net.minecraft.server.MinecraftServer.run(SourceFile:605)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:74)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at zm.a(SourceFile:505)
        ... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.14.2
        Operating System: Linux (amd64) version 5.0.0-17-generic
        Java Version: 11.0.3, Ubuntu
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
        Memory: 682485488 bytes (650 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
        JVM Flags: 4 total; -Xms1024M -Xmx1024M -XX:+UseConcMarkSweepGC -XX:+AggressiveOpts
        Data Packs:
        Is Modded: Unknown (can't tell)
        Type: Dedicated Server (map_server.txt)

I have loaded the map into my client and it starts fine, no issue as the day I last logged out on my server. I've read that it means one of my JSON file has an issue. I have verified all files have persmissions with:

 sudo useradd minecraft --home /opt/msm
 sudo chown minecraft /opt/msm
 sudo chmod -R 775 /opt/msm

and then backing that up with 'ls -l' and verify permission manually (completely unnecessary I am sure but I am at a loss). By the fact it calls for line 1 column 1, makes me think it is an empty file causing the issue. This doesn't happen when I create a new server from scratch ('$sudo msm server create main' would work fine.) I have been at it all day so I give up for now but I really hope I have give you all the information. I guess I could delete all the empty JSON files and let it rebuilt them but I thought I'd post here to see which way to go further. It also bothered me I had to remove a line from the startup when yesterday my server didn't make me. Maybe an underlying related issue? 

Here are the version of everything:

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu219.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu219.04.1, mixed mode, sharing)

Minecraft Server Manager 0.9.10 Beta

Minecraft 1.14.2

 Ubuntu Server 19.04

Any help would be much appreciated. Thank you.

**Comment by endofcake** [comment]
Look like Java crashes when it tries to read one of the config files, can you try creating a new server with a fresh set of config files?
