### ISSUE TITLE
Player data does not persist

### ISSUE THREAD

**Issue by mansdahlstrom1** [msmhq/msm#383]
I have problem with saving my world, Specifily the playerdata gets reset to the invertory that existed when the world was created.

The Server is running on Ubuntu 16, and the world we are running was first created on a mac then moved over to the server by with `scp`. Everything works fine, and the server saves all blocks correctly. By looking at the logs i can see that i'm getting this issue a lot `The save is being accessed from another location, aborting`. The server warn about this a lot in the logs. I've tried double check that the "minecraft" user owns every file/ directory in the Server catalogue and also added full permission to edit and read all files in the "worldstorage" folder. 

Feels like i've tried everything i can think of now and the issue persists. 

Not sure if this is an issue with MSM or if it's just a minecraft server thing. Anyone how knows why this is happening?

Thanks

**Comment by endofcake** [comment]
This sounds like an issue with migration from Mac, nothing MSM specific.
