### ISSUE TITLE
I have an engine issue

### ISSUE THREAD

**Issue by IFerrr** [msmhq/msm#386]
every single time i attempt to open my server it says Error: Invalid or corrupt jarfile engine.jar Ive tried creating a a new server, ive tried opening the jar directly and i got the same error message. i tried everything i can think of. any solutions?

**Comment by endofcake** [comment]
Where is `engine.jar` coming from? Have you tried replacing this file?

**Comment by endofcake** [comment]
Closing as no further information provided.
