### ISSUE TITLE
Feature Request: Use ServerJars api to get latest server jars

### ISSUE THREAD

**Issue by Element21** [msmhq/msm#393]
I just found the site serverjars.com and saw it has a server jar fetching api. Could we implement this in msm?

**Comment by bmr549** [comment]
This can already be done using the jargroup functionality of MSM.

The command `msm jargroup create <name> <download-url>` will automatically pull jar files from the given download link. ServerJars provides a simple API endpoint that can be placed into the `<download-url>` parameter: `https://serverjars.com/api/{requestDetails}`, where `{requestDetails}` are commands following the [documentation](https://serverjars.com/documentation).

The specific API request that you may be looking for is `https://serverjars.com/api/fetchJar/{type}` which gives a direct download link to the latest jar, exactly what is needed for the jargroup functionality of MSM.

As an example, if you wanted to setup a jargroup for Spigot and assign it to a server the commands would be:
```
msm jargroup create spigot https://serverjars.com/api/fetchJar/spigot
<server> jar spigot
```

**Comment by Element21** [comment]
Thanks!
