### ISSUE TITLE
Fix bash variable expansion for Debian installer

### ISSUE THREAD

**Issue by renderorange** [msmhq/msm#400]
Debian 9
Bash 4.4.12(1)

```
# bash /tmp/msm
(...)
MSM INSTALL: Updating sources
/tmp/msm: line 11: [: too many arguments
```
```
if [ $NAME == 'Ubuntu' ]; then
```

This is happening because the `$NAME` variable in `/etc/os-release` contains a space
```
NAME="Debian GNU/Linux"
```
which expands the string into 2 parts, which the `[` program fails on.

Double quoting the `$NAME` variable fixes the issue.

**Comment by endofcake** [comment]
Merged.
