### ISSUE TITLE
Remove invalid java invocation arguments

### ISSUE THREAD

**Issue by renderorange** [msmhq/msm#402]
The `UseConcMarkSweepGC`, `CMSIncrementalPacing`, and `AggressiveOpts` arguments are no longer supported in current versions of Java.

Additionally, with those options in place, minecraft server fails to start, but doesn't indicate it failed to the console.  The `eula.txt` is not generated and logs are not created for the user to troubleshoot why the server isn't actually running.

Removing `UseConcMarkSweepGC`, `CMSIncrementalPacing`, and `AggressiveOpts` allows java to generate the eula on the first start.  `msm` then detects the eula is not accepted and informs the user to accept before it will starts the server.

**Comment by endofcake** [comment]
PR merged.
