### ISSUE TITLE
Enable msmhq/msm on Travis

### ISSUE THREAD

**Issue by renderorange** [msmhq/msm#411]
https://travis-ci.org/github/msmhq/msm

```
 This is not an active repository

You don't have sufficient rights to enable this repo on Travis.
Please contact the admin to enable it or to receive admin rights yourself. 
```

Whomever has rights to add the msm repo to Travis, would you please enable?

**Comment by endofcake** [comment]
I looked into this a while ago and couldn't do it, likely due to the lack of permissions.
We may have to migrate it to something like GitHub Actions.

**Comment by endofcake** [comment]
I've added a GitHub Actions manifest. It may not be perfect, but it worked in my fork and we can iterate on it.
