### ISSUE TITLE
Changing the msm location

### ISSUE THREAD

**Issue by kaydenharris** [msmhq/msm#419]
I misplaced my directory in a system folder which harder to give permissions to, I am trying to change the location so the terminal can get permissions.

**Comment by renderorange** [comment]
Hi, can you elaborate on what you mean by `misplaced my directory`?  What commands did you use to move it?

If you had the rights to move it there, are you not able to move it back?  What commands have you tried to move it back?

**Comment by endofcake** [comment]
This issue has become stale. Closing.
