### ISSUE TITLE
Version tag 0.10.0 is outside msm's repository, and does not include updates to changelog merged in PR #416

### ISSUE THREAD

**Issue by Next-Door-Tech** [msmhq/msm#436]
The Issue
---
Tag [0.10.0](https://github.com/msmhq/msm/releases/tag/0.10.0) currently points to commit 28642095548d159b934784343099c430d496e4d2, which is actually not to a member of the proper [msmhq/msm](https://github.com/msmhq/msm/) repository (I'm actually not 100% sure where it *does* belong). The corresponding commit actually on the tree is 6c1d8c7c651de35145b865448853f01e30ce3dc6.

Additionally, Pull Request #416 `Fix change log entry for version 0.10.0` was merged downstream of Tag [0.10.0](https://github.com/msmhq/msm/releases/tag/0.10.0). This means that the commit with the correct changelog for 0.10.0 is actually several commits *ahead* of where the tag points, and the tag currently does *not* have the correct changelog. The commit with the correct changelog for 0.10.0 is 5c28b6fc5c41d9f55a22b078899aefeb4ba08584.

How to Resolve
---
The existing Tag [0.10.0](https://github.com/msmhq/msm/releases/tag/0.10.0) (pointing to 28642095548d159b934784343099c430d496e4d2) first needs to be deleted, and then a new Tag 0.10.0 pointing to  6c1d8c7c651de35145b865448853f01e30ce3dc6 needs to be created in its place.

Unfortunately, I can't create a pull request for deleting or creating a tag; this needs to be done directly by one of the msm repository maintainers.

As a side note, if you merge Pull Request #432 before doing this, you also fix issue #435 at the same time.

**Comment by antoinelafontaine** [comment]
It would be nice to see those pull request accepted...

**Comment by endofcake** [comment]
Tag 0.10.0 movet to now point to https://github.com/msmhq/msm/commit/5c28b6fc5c41d9f55a22b078899aefeb4ba08584.
