### ISSUE TITLE
WorldEdit 

### ISSUE THREAD

**Issue by Crinisen** [msmhq/msm#55]
I am having a hard time getting world edit to allow me to restore from the backups created with this tool.

Example: if my archive path for msm is:
WORLD_ARCHIVE_PATH="/opt/msm/archives/worlds"

and I change the config.yml for world edit to be:

snapshots:
    directory: "/opt/msm/archives/worlds/"

I get 'no snapshots found' when I run a "//snap list"

What am I doing wrong here?  I have files in /opt/msm/archives/worlds/myworld/[data/region/players] folders

**Comment by Milesbreen** [comment]
Hello! I was wondering how to install worldedit on linux msm. Any tricks?
