### ISSUE TITLE
Plugins not loading or being initialized with CraftBukkit

### ISSUE THREAD

**Issue by Routhinator** [msmhq/msm#85]
Hi, 

I've install MSM with CraftBukkit 1.3.1, and I've added two bukkit plugins. (Citizens and LoginMessage) - However neither plugin is being initialized by the Craftbukkit server with MSM.

I tried manually creating a server with the same CraftBukkit and the plugins without MSM, and plugins were initialized (config.yml files were created) however they won't initialize with MSM. Also MSM + CraftBukkit only seems to see one of the 2 plugins when I use the /plugins command (citizens plugin is seen, LoginMessage in not recognized)

Is there something I'm missing with MSM + CraftBukkit setup?

**Comment by SaltierThanSalt** [comment]
im someone in earth

**Comment by SaltierThanSalt** [comment]
btw, if you are having problems with the permission denied,
do "sudo (code here)"
and change the (code here) to the code you are using
